compressionLevel: mixed

packageExtensions:
  '@testing-library/react@*':
    dependencies:
      react: '18.2.0'
      react-dom: '18.2.0'

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-remote.cjs
